CREATE TABLE "T_Category" (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  createdById VARCHAR(32) NOT NULL REFERENCES "T_User"(id),
  createdByName VARCHAR(32) NOT NULL,
  updatedById VARCHAR(32) NOT NULL REFERENCES "T_User"(id),
  updatedByName VARCHAR(32) NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE NOT NULL,
  updatedAt TIMESTAMP WITH TIME ZONE NOT NULL,
  deletedAt TIMESTAMP WITH TIME ZONE NOT NULL,
  name VARCHAR(64) NOT NULL
);
