CREATE TABLE "T_TodoList"(
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  createdById VARCHAR(32) NOT NULL REFERENCES "T_User"(id),
  createdByName VARCHAR(32) NOT NULL,
  updatedById VARCHAR(32) NOT NULL REFERENCES "T_User"(id),
  updatedByName VARCHAR(32) NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE NOT NULL,
  updatedAt TIMESTAMP WITH TIME ZONE NOT NULL,
  deletedAt TIMESTAMP WITH TIME ZONE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  isCompleted BOOLEAN NOT NULL DEFAULT FALSE,
  sort INTEGER DEFAULT 0
);

-- DROP TABLE "T_TodoList"
